// <auto-generated />
using System;
using HotelManagementSystem.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelManagementSystem.Data.Migrations
{
    [DbContext(typeof(HotelManagementDbContext))]
    [Migration("20260227054214_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("HotelManagementSystem.Data.Models.CheckInOut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CheckInBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CheckOutBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReservationId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CheckInBy");

                    b.HasIndex("CheckOutBy");

                    b.HasIndex("ReservationId");

                    b.ToTable("CheckInOuts");
                });

            modelBuilder.Entity("HotelManagementSystem.Data.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("HotelManagementSystem.Data.Models.HotelService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("HotelServices");
                });

            modelBuilder.Entity("HotelManagementSystem.Data.Models.MaintenanceTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedTo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("MaintenanceTasks");
                });

            modelBuilder.Entity("HotelManagementSystem.Data.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAnnouncement")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecipientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecipientType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SenderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("HotelManagementSystem.Data.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReservedBy")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReservedByNavigationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ReservedByNavigationId");

                    b.HasIndex("RoomId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("HotelManagementSystem.Data.Models.ReservationService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AddedBy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HotelServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReservationId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("HotelServiceId");

                    b.HasIndex("ReservationId");

                    b.ToTable("ReservationServices");
                });

            modelBuilder.Entity("HotelManagementSystem.Data.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("HotelManagementSystem.Data.Models.RoomCleaning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CleanedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CleaningDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CleanedBy");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomCleanings");
                });

            modelBuilder.Entity("HotelManagementSystem.Data.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("HotelManagementSystem.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HotelManagementSystem.Data.Models.CheckInOut", b =>
                {
                    b.HasOne("HotelManagementSystem.Data.Models.User", "CheckInByNavigation")
                        .WithMany("CheckInOutCheckInByNavigations")
                        .HasForeignKey("CheckInBy");

                    b.HasOne("HotelManagementSystem.Data.Models.User", "CheckOutByNavigation")
                        .WithMany("CheckInOutCheckOutByNavigations")
                        .HasForeignKey("CheckOutBy");

                    b.HasOne("HotelManagementSystem.Data.Models.Reservation", "Reservation")
                        .WithMany("CheckInOuts")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckInByNavigation");

                    b.Navigation("CheckOutByNavigation");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("HotelManagementSystem.Data.Models.Customer", b =>
                {
                    b.HasOne("HotelManagementSystem.Data.Models.User", "User")
                        .WithMany("Customers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelManagementSystem.Data.Models.MaintenanceTask", b =>
                {
                    b.HasOne("HotelManagementSystem.Data.Models.User", "Staff")
                        .WithMany("MaintenanceTaskAssignedToNavigations")
                        .HasForeignKey("AssignedTo");

                    b.HasOne("HotelManagementSystem.Data.Models.Room", "Room")
                        .WithMany("MaintenanceTasks")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagementSystem.Data.Models.User", null)
                        .WithMany("MaintenanceTaskApprovedByNavigations")
                        .HasForeignKey("UserId");

                    b.Navigation("Room");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("HotelManagementSystem.Data.Models.Notification", b =>
                {
                    b.HasOne("HotelManagementSystem.Data.Models.User", "Recipient")
                        .WithMany("NotificationRecipients")
                        .HasForeignKey("RecipientId");

                    b.HasOne("HotelManagementSystem.Data.Models.User", "Sender")
                        .WithMany("NotificationSenders")
                        .HasForeignKey("SenderId");

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("HotelManagementSystem.Data.Models.Reservation", b =>
                {
                    b.HasOne("HotelManagementSystem.Data.Models.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagementSystem.Data.Models.User", "ReservedByNavigation")
                        .WithMany("Reservations")
                        .HasForeignKey("ReservedByNavigationId");

                    b.HasOne("HotelManagementSystem.Data.Models.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("ReservedByNavigation");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelManagementSystem.Data.Models.ReservationService", b =>
                {
                    b.HasOne("HotelManagementSystem.Data.Models.HotelService", "HotelService")
                        .WithMany("ReservationServices")
                        .HasForeignKey("HotelServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagementSystem.Data.Models.Reservation", "Reservation")
                        .WithMany("ReservationServices")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HotelService");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("HotelManagementSystem.Data.Models.RoomCleaning", b =>
                {
                    b.HasOne("HotelManagementSystem.Data.Models.User", "CleanedByNavigation")
                        .WithMany("RoomCleanings")
                        .HasForeignKey("CleanedBy");

                    b.HasOne("HotelManagementSystem.Data.Models.Room", "Room")
                        .WithMany("RoomCleanings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CleanedByNavigation");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelManagementSystem.Data.Models.Staff", b =>
                {
                    b.HasOne("HotelManagementSystem.Data.Models.User", "User")
                        .WithMany("Staff")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelManagementSystem.Data.Models.Customer", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("HotelManagementSystem.Data.Models.HotelService", b =>
                {
                    b.Navigation("ReservationServices");
                });

            modelBuilder.Entity("HotelManagementSystem.Data.Models.Reservation", b =>
                {
                    b.Navigation("CheckInOuts");

                    b.Navigation("ReservationServices");
                });

            modelBuilder.Entity("HotelManagementSystem.Data.Models.Room", b =>
                {
                    b.Navigation("MaintenanceTasks");

                    b.Navigation("Reservations");

                    b.Navigation("RoomCleanings");
                });

            modelBuilder.Entity("HotelManagementSystem.Data.Models.User", b =>
                {
                    b.Navigation("CheckInOutCheckInByNavigations");

                    b.Navigation("CheckInOutCheckOutByNavigations");

                    b.Navigation("Customers");

                    b.Navigation("MaintenanceTaskApprovedByNavigations");

                    b.Navigation("MaintenanceTaskAssignedToNavigations");

                    b.Navigation("NotificationRecipients");

                    b.Navigation("NotificationSenders");

                    b.Navigation("Reservations");

                    b.Navigation("RoomCleanings");

                    b.Navigation("Staff");
                });
#pragma warning restore 612, 618
        }
    }
}
